global:
  proxy:
    autoInject: enabled
  proxy_init:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

meshConfig:
  accessLogFile: "/dev/stdout"

pilot:
  autoscaleEnabled: true

telemetry:
  v2:
    enabled: true

gateways:
  istio-ingressgateway:
    enabled: true
    service:
      type: ClusterIP
      ports:
        - name: http2
          port: 80
          targetPort: 8080
        - name: https
          port: 443
          targetPort: 8443
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 1
        memory: 1Gi

sidecarInjectorWebhook:
  enabled: true
