prometheus:
  prometheusSpec:
    retention: "15d"
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
grafana:
  adminPassword: "SECURE_PASSWORD"
  persistence:
    enabled: true
    size: 20Gi
  ingress:
    enabled: false
