apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/managed-by: terraform
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  source:
    repoURL: https://github.com/pujithakondaveeti/aksmesh.git
    targetRevision: main
    path: apps/demo
    kustomize:
      namePrefix: ""
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
